#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: Service
metadata:
  namespace: fizz
  name: questions
spec:
  selector:
    app: questions
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9003
