#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fizz
  name: idm
data:
  FIZZ_IDM_SVC_PORT: "9002"
  FIZZ_IDM_CRYPTO_MTLS_SERVER_ADDRESS: "fizz-crypto.fizz.svc.cluster.local"
  FIZZ_IDM_MAILER_MTLS_SERVER_ADDRESS: "fizz-mailer.fizz.svc.cluster.local"
  FIZZ_IDM_JWT_COOKIE_EXPIRY_HOURS: "700"
  FIZZ_IDM_USERS_TABLE_NAME: "users"
  FIZZ_IDM_DB_NAME: "fizz"
  FIZZ_IDM_VERIFIED_URL: "https://fizzbuzz.pro/verified"
  FIZZ_IDM_PATH_PREFIX: "/idm"
  FIZZ_IDM_SERVICE_NAME: "fizz-idm"
  FIZZ_IDM_LAUNCH_STATE: "waitlist"
