#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: Secret
metadata:
  namespace: fizz
  name: store
data:
  FIZZ_STORE_HONEYBADGER_API_KEY: "YmFkZ2Vy"
  FIZZ_STORE_STRIPE_PRIVATE_KEY: "YmFkZ2Vy"
  FIZZ_STORE_STRIPE_PUBLIC_KEY: "YmFkZ2Vy"
