#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fizz
  name: questions
data:
  FIZZ_QUESTIONS_SVC_PORT: "9003"
  FIZZ_QUESTIONS_DATA_PATH: "/path/to/data"
  FIZZ_QUESTIONS_PATH_PREFIX: "/questions"
  FIZZ_QUESTIONS_SERVICE_NAME: "fizz-questions"
