#  \
#  \\,
#   \\\,^,.,,.                     Zero to Hero
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

apiVersion: v1
kind: Service
metadata:
  namespace: fizz
  name: mailer
spec:
  selector:
    app: mailer
  ports:
    - port: 80
      targetPort: 9005
  type: ClusterIP
